[package]
name = "rust-mini-gpt"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "0.49.1", features = ["lazy"] }
tch = "0.20.0"
tokenizers = { version = "0.21.2", features = ["http"] }
regex = "1.10"
